theme: jekyll-theme-architect
logo: /assets/img/logo.jpg
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
relative_links:
  enabled: true
  collections: true
include:
 - index.md
