theme: jekyll-theme-minimal
logo: /assets/img/logo.png
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
relative_links:
  enabled: true
  collections: true
include:
 - index.md
